name: First Workflow checking

on:
  push:
    branches: ["workflow"]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!1"
          echo "Hello World!3"
      - name: Print goodbye
        run: echo "Done - bye!"
