name: pullOPen
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{toJson(github)}}"
